#lang scheme
(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (display "current guess is ")
    (display v1)
    (display ", next:")
    (newline)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? guess next)
        next
        (try next))))
  (try first-guess))
; Exercise 1.35
(define (gold-div)
  (fixed-point  (lambda (y) (+ 1.0 (/ 1.0 y)))
                1.0))
(gold-div)
(newline)
; Exercise 1.36
(define (power-self-1000)
  (fixed-point  (lambda (x) (/ (log 1000) (log x)))
                1.5))
(power-self-1000)

; Exercise 1.37
(define (cont-frac n d k)
  (define (iter count)
    (if (= count k)
        (/ (n count) (d count))
        (+  (d count)
            (/  (n count)
                (iter (+ count 1))))))
  (iter 1))
(cont-frac  (lambda (i) 1.0)
            (lambda (i) 1.0)
            50)
(define (frac-cont n d k)
  (define (iter count result)
    (display result)
    (newline)
    (if (= count k)
      result
      (iter (+ count 1) (/ (n count) (+ (d count) result)))))
  (iter 1 (/ (n 1) (d 1))))
(frac-cont  (lambda (i) 1.0)
            (lambda (i) 1.0)
            30)