#lang scheme
; Exercise 1.9. Each of the following two procedures defines a method for adding two positive integers
; in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its
; argument by 1.
; (define (+ a b)
;   (if (= a 0)
;   b
;   (inc (+ (dec a) b))))

; (define (+ a b)
;   (if (= a 0)
;   b
;   (+ (dec a) (inc b))))
; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4
; 5). Are these processes iterative or recursive?

; first
; (+ 4 5)
; (inc (+ 3 5))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9

; second
; (+ 4 5)
; (+ 3 6)
; (+ 2 7)
; (+ 1 8)
; (+ 0 9)
; 9

; Exercise 1.10. The following procedure computes a mathematical function called Ackermann’s
; function.
(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A  (- x 1)  
                  (A x (- y 1))))))
; What are the values of the following expressions?
(A 1 10)  ; 1024
(A 2 1)   ; 2
(A 2 2)   ; 4
(A 2 3)   ; 16
(A 2 4)   ; 65536
; (A 2 5) ; ... 2^(2^(2^(2^2)))
(A 3 1)   ; 2
(A 3 2)   ; 4
(A 3 3)   ; 65536
; Consider the following procedures, where A is the procedure defined above:
(define (f n) (A 0 n))  ; 2*n
(define (g n) (A 1 n))  ; 2^n
(define (h n) (A 2 n))  ; 2^(2^(2^(2^2)))...
(define (k n) (* 5 n n)); 5*(n^2)
; Give concise mathematical definitions for the functions computed by the procedures f, g, and h for
; positive integer values of n. For example, (k n) computes 5n2 .